version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  smtp:
    image: bytemark/smtp
    restart: always
#    ports:
#      - "2525:25"
  gophish:
    image: gophish/gophish
    ports:
      - "3333:3333"
      - "8080:80"
    volumes:
      - ./config.json:/opt/gophish/config.json
      - ./database/:/opt/gophish/database/
    environment:
      - ADMIN_PORT=3333
      - PHISHING_PORT=80
    depends_on:
      - smtp